config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root to: 'posts#index'

   	get '/admin' => 'admin/sessions#new'
  	get '/login' => 'admin/sessions#index'
  	get '/logout' => 'admin/sessions#destroy'

  	get 'admin/images/list' => 'admin/images#list'
  	get 'admin/photos/list' => 'admin/photos#list'

	namespace :admin do
		resources :dashboard, only: [:index]
		resources :sessions, only: [:index, :create, :destroy]
		resources :moderators, only: [:index, :new, :create, :edit, :update]
		resources :articles do
      collection do
        patch :reorder
      end
    end
		#resources :services, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :partners, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]
    #resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :sections do
      collection do
        patch :reorder
      end
    end
	end
end

app/models/moderator.rb
class Moderator < ApplicationRecord
	has_secure_password
	
	validates :fullname, presence: true
	validates :username, presence: true
	validates :password, presence: true, length: { minimum: 6 }	
end

app/controllers/admin/moderators_controller.rb
class Admin::ModeratorsController < Admin::ApplicationController

	def index
		@moderators = Moderator.all
	end

	def new
    	@moderator = Moderator.new
    end

	def edit
		@moderator = Moderator.find(params[:id])
	end

	def create
    	@moderator = Moderator.new(moderator_params)
    	respond_to do |format|
      		if @moderator.save
        		format.html { redirect_to admin_moderators_url, notice: 'Administrator' + moderator_params[:fullname] + 'ble opprettet.' }
        		format.json { render :show, status: :created, location: @moderator }
      		else
       			format.html { render :new }
        		format.json { render json: @moderator.errors, status: :unprocessable_entity }
      		end
    	end
  	end

	def update
		@moderator = Moderator.find(params[:id])

		if 	@moderator.update(moderator_params)
			flash[:notice] = "Moderator was successfully updated."
			redirect_to admin_moderators_url
		else
			flash[:alert] = "There was a problem updating Moderator."
			render 'edit'
		end

	end

	private
		def moderator_params
			params.require(:moderator).permit(:id, :fullname, :username, :password)
		end
end

app/views/admin/moderators/_form.html.erb
<%= form_for [:admin, @moderator], :html => {:id => 'identicalForm' } do |f| %>
  <% if @moderator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moderator.errors.count, "error") %> prohibited this admin_department from being saved:</h2>

      <ul>
      <% @moderator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="tabs-container">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">Brukernavn</a></li>
        <li class=""><a data-toggle="tab" href="#tab-2" aria-expanded="false">Passord</a></li>
    </ul> 
    <div class="tab-content">
        <div id="tab-1" class="tab-pane active">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :fullname, 'Navn', :class => "" %>
              <%= f.text_field :fullname, :class => 'form-control', :placeholder => "Fullt navn" %>
            </div>
            <div class="form-group">
              <%= f.label :username, 'Brukernavn/Epost', :class => "" %>
              <%= f.text_field :username, :class => 'form-control', :placeholder => "Brukernavn" %>
            </div> 
          </div><!-- /panel-body -->
        </div><!-- /tab-pane -->
        <div id="tab-2" class="tab-pane">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :password, 'Passord', :class => "" %>
              <%= f.password_field :password, {:class => 'form-control', :placeholder => 'Passord', 'data-bv-identical' => 'true', 'data-bv-identical-field' => 'confirmPassword', 'data-bv-identical-message' => 'The password and its confirm are not the same' } %>
            </div>
            <div class="form-group">
              <label class="control-label">Gjenta passord</label>
              <input type="password" class="form-control" name="confirmPassword"
                  data-bv-identical="true"
                  data-bv-identical-field="moderator[password]"
                  data-bv-identical-message="The password and its confirm are not the same" />
            </div>
          </div><!-- /panel-body -->
        </div><!-- /tab-pane -->

        <div class="actions" style="margin-top:20px;">
          <%= f.submit 'Lagre administrator', :class => 'btn btn-primary' %>
          
        </div>

      </div><!-- /tab-content -->

  </div><!-- /tabs-container -->
<% end %>

app/views/admin/moderators/edit.html.erb
<div class="col-lg-8">
    <div class="ibox">
        <div class="ibox-title">
            <h5>Administrator profil</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="fullscreen-link">
                    <i class="fa fa-expand"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">

        	<%= render 'form'%>
        	
        </div>
    </div>
</div>

app/views/admin/moderators/index.html.erb
<div class="ibox">
	<div class="ibox-title"><h2><i class="fa fa-user-lock"></i> Administratorer</h2></div>
    <div class="ibox-content">
        <div class="panel-body">
			<table class="table table-bordered table-hover">
				<thead>
					<tr>
						<th>Fullt navn</th>
						<th>Brukernavn</th>
						
						<th colspan="2">Handlinger</th>
					</tr>
				</thead>
				<tbody>
					<% @moderators.each do |moderator| %>
					<tr>
						<td><%= moderator.fullname %></td>
						<td><%= moderator.username %></td>
						
						<td>
							<%= link_to 'Endre', edit_admin_moderator_path(moderator), :class => 'btn btn-info btn-xs' %>
						</td>
						<td>
							<%= link_to 'Slette', "#", :class => 'btn btn-danger btn-xs' %>
								
							</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<br>
			<%= link_to 'Ny administrator', new_admin_moderator_path, :class => 'btn btn-primary' %>
		</div>
	</div>
</div>

app/views/admin/moderators/new.html.erb
<div class="col-lg-8">
    <div class="ibox">
        <div class="ibox-title">
            <h5>Legge til ny administrator</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="fullscreen-link">
                    <i class="fa fa-expand"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">

        	<%= render 'form'%>
        	
        </div>
    </div>
</div>