config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root to: 'posts#index'

   	get '/admin' => 'admin/sessions#new'
  	get '/login' => 'admin/sessions#index'
  	get '/logout' => 'admin/sessions#destroy'

  	get 'admin/images/list' => 'admin/images#list'
  	get 'admin/photos/list' => 'admin/photos#list'

	namespace :admin do
		resources :dashboard, only: [:index]
		resources :sessions, only: [:index, :create, :destroy]
		resources :moderators, only: [:index, :new, :create, :edit, :update]
		resources :articles do
      collection do
        patch :reorder
      end
    end
		#resources :services, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :partners, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]
    #resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :sections do
      collection do
        patch :reorder
      end
    end
	end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :section

   scope :published, -> { where(ispublished: true).order(id: :desc) }

   scope :ordered, -> { where(ispublished: true, :section_id => '2').order(:position) }

   scope :facts, -> { where(ispublished: true, :section_id => '3').order(:position) }

   mount_uploader :image, ImageUploader

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]

  def index
   # @articles = Article.where(:section_id => params[:cat])
    @articles = Article.where(:section_id => params[:cat]).order(position: :asc)
  end

  def reorder
    params[:article].each_with_index do |id, index|
      Article.where(id: id).update_all(position: index + 1) 
    end
    head :ok
  end    

  def new
    @article = Article.new(:section_id => params[:cat])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_articles_url(:cat => @article.section_id), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_url(:cat => @article.section_id), notice: 'Artikkelen: ' + article_params[:title] + ' ble oppdatert!'
    else
      flash[:alert] = 'Det var et problem med oppdateringen'
      render :edit
    end   
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_url(:cat => @article.section_id), notice: 'Artikkelen ble slettet!'
  end

  private

    def set_admin_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :content, :image, :ispublished, :section_id, :remove_image, :template, :position)
    end

end

app/views/admin/articles/_form.html.erb
<input type="hidden" id="articleID" value="<%= @article.id %>">
<%= form_for [:admin, @article], html: { multipart: true } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this admin_article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="article[section_id]" id="article_section_id" value="<%= params[:cat] %>" />
  <div class="col-md-9">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :title, 'Tittel', :class => "" %>
          <%= f.text_field :title, :class => 'form-control', :placeholder => "Tittel" %>
        </div>
      </div>  
    </div>      
    <div class="form-group">
      <%= f.label :summary, 'Ingress' %><br>
      <%= f.text_area :summary, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :content, 'Brødtekst' %><br>
      <%= f.text_area :content, :class => "summernote" %>
    </div>

  </div>
 
  <!-- aside right-->
  <div class="col-sm-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= f.submit 'Lagre', :class => "btn btn-primary btn-block" %>
      </div>
      <div class="panel-body">
        <div class="checkbox checkbox-primary">
          <%= f.check_box :ispublished, :class => "" %>
          <%= f.label :ispublished, 'Publisere' %>
        </div>
      </div>

      <div class="panel-footer">
        <span class="text-muted small">
          Opprettet: <%= @article.created_at.to_s(:long) if @article.created_at? %><br>
          Sist oppdatert: <%= @article.updated_at.to_s(:long) if @article.updated_at? %>
        </span> 
      </div>
    </div>
    <div class="form-group">
      <%= f.label :template, 'Velg mal: ', :class => '' %>
      <%= f.select :template, 
        [['Velg mal', 'default'],
          ['Halvside (Venstrestilt bilde)', 'half-page-image-left'],
          ['Halvside (høyrestilt bilde)', 'half-page-image-right'],
          ['Kontakt (Venstrestilt bilde)', 'contact-page-image-left'],
          ['Kontakt (høyrestilt bilde)', 'contact-page-image-right']          
        ], 
          {}, :class => "form-control" %>      
    </div> 
    <div class="panel panel-default">
      <div class="panel-heading">
        Hovedbilde
      </div>
      <div class="panel-body">
      
        <div class="img-responsive" id="image-holder">
          <%= image_tag @article.image_url(:thumb) if @article.image?%>
        </div>
      
      </div>
      <div class="panel-footer">
        <%= f.label :image, :class => "btn btn-info btn-block" do %>
          <%= f.file_field :image, :class => 'hide'%>Velg bilde
        <% end %>  
      </div>  
    </div>
  <% end %>


  </div>


<script type="text/javascript">
  $(function() {
    $('.summernote').summernote({
      height: 200,
      tabsize: 4,
      toolbar: [
                 ["style", ["style"]],
                 ["style", ["bold", "italic", "underline", "clear"]],
                 ["table", ["table"]],
                 ["para", ["ul", "ol", "paragraph"]],
                 ['extensions', ['gallery']],
                 ['insert', ['videoAttributes']],  
                 ['insert', ['link']],  
                 ['insert', ['hr']]
                 
             ],
        callbacks :{
             onInit: function() {
                $(this).data('image_dialog_images_url', '<%= admin_photos_list_url %>');
                $(this).data('image_dialog_title', "Bilde galleri");
                $(this).data('image_dialog_close_btn_text', "Lukk");
                $(this).data('image_dialog_ok_btn_text', "Ok");
            }
        }             
      });
    });
  </script>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#article_image").on('change', function() {
        var countFiles = $(this)[0].files.length;
        var imgPath = $(this)[0].value;
        var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
        var image_holder = $("#image-holder");
        image_holder.empty();
        if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
          if (typeof(FileReader) != "undefined") {
            //loop for each file selected for uploaded.
            for (var i = 0; i < countFiles; i++) 
            {
              var reader = new FileReader();
              reader.onload = function(e) {
                $("<img />", {
                  "src": e.target.result,
                  "class": "thumb-image"
                }).appendTo(image_holder);
              }
              image_holder.show();
              reader.readAsDataURL($(this)[0].files[i]);
            }
          } else {
            alert("This browser does not support FileReader.");
          }
        } else {
          alert("Pls select only images");
        }
      });
    });
  </script>

app/views/admin/articles/edit.html.erb
	<%= render 'form' %>

app/views/admin/articles/index.html.erb
<div class="ibox">
  <div class="ibox-content">
    <div class="panel-body">  
      <h4>Artikler</h4>
      <div id="articles" class="list-group" data-url="<%= reorder_admin_articles_path %>">
        <% @articles.each do |article| %>
          <div id="<%= dom_id(article) %>" class="list-group-item">
            <%= link_to article.title, edit_admin_article_path(article, :cat => article.section_id) %>  
            <span class="badge badge-danger">
              <span><%= article.position %></span>
                <%= link_to 'Slett', admin_article_path(article), method: :delete, data: { confirm: 'Er du sikker?' }, :style => 'color:#fff;' %>  
            </span>
          </div>
        <% end %>
      </div>

      <br>

      <%= link_to 'Ny artikkel', new_admin_article_path(:cat => params[:cat]), :class => 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
	<%= render 'form' %>