config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root to: 'posts#index'

   	get '/admin' => 'admin/sessions#new'
  	get '/login' => 'admin/sessions#index'
  	get '/logout' => 'admin/sessions#destroy'

  	get 'admin/images/list' => 'admin/images#list'
  	get 'admin/photos/list' => 'admin/photos#list'

	namespace :admin do
		resources :dashboard, only: [:index]
		resources :sessions, only: [:index, :create, :destroy]
		resources :moderators, only: [:index, :new, :create, :edit, :update]
		resources :articles do
      collection do
        patch :reorder
      end
    end
		#resources :services, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :partners, only: [:index, :new, :create, :edit, :update, :destroy]
		#resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]
    #resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :sections do
      collection do
        patch :reorder
      end
    end
	end
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :articles
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::ApplicationController
  before_action :set_admin_section, only: [:show, :edit, :update, :destroy]
 
  def index
    @sections = Section.order(:position)
  end
 
  def reorder
    params[:section].each_with_index do |id, index|
      Section.where(id: id).update_all(position: index + 1)
    end
    head :ok
  end

  def new
    @section = Section.new
  end

  def edit

  end

  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to admin_sections_url, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to edit_admin_section_url@section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to admin_sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_section
      @section = Section.find(params[:id])
    end

    def section_params
      params.require(:section).permit(:title, :description, :position, :ispublished)
    end
end

app/views/admin/sections/_form.html.erb
<%= form_for [:admin, @section] do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Seksjon', :class => "" %>
    <%= f.text_field :title, :class => 'form-control', :placeholder => "Seksjonsnavn" %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Beskrivelse' %><br>
     <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Lagre seksjon', :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/sections/edit.html.erb
	<%= render 'form' %>

app/views/admin/sections/index.html.erb
<div class="ibox">
  <div class="ibox-content">
    <div class="panel-body">  
      <h4>Seksjoner</h4>
      <div id="sections" class="list-group" data-url="<%= reorder_admin_sections_path %>">
        <% @sections.each do |section| %>
          <div id="<%= dom_id(section) %>" class="list-group-item">
            <%= link_to section.title, edit_admin_section_path(section) %>  
            <span class="badge badge-danger">
                <%= link_to 'Slett', admin_section_path(section), method: :delete, data: { confirm: 'Er du sikker?' }, :style => 'color:#fff;' %>  
            </span>
          </div>
        <% end %>
      </div>
     
      <br>

      <%= link_to 'Ny seksjon', new_admin_section_path(:cat => params[:cat]), :class => 'btn btn-sm btn-info' %>

    </div>
  </div>
</div>

app/views/admin/sections/new.html.erb
	<%= render 'form' %>